// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: steammessages_video.steamclient.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Steam.Messages.Video {

  /// <summary>Holder for reflection information generated from steammessages_video.steamclient.proto</summary>
  public static partial class SteammessagesVideoSteamclientReflection {

    #region Descriptor
    /// <summary>File descriptor for steammessages_video.steamclient.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SteammessagesVideoSteamclientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVzdGVhbW1lc3NhZ2VzX3ZpZGVvLnN0ZWFtY2xpZW50LnByb3RvGhhzdGVh",
            "bW1lc3NhZ2VzX2Jhc2UucHJvdG8aLHN0ZWFtbWVzc2FnZXNfdW5pZmllZF9i",
            "YXNlLnN0ZWFtY2xpZW50LnByb3RvIoEBCiBDVmlkZW9fQ2xpZW50R2V0Vmlk",
            "ZW9VUkxfUmVxdWVzdBIeCgh2aWRlb19pZBgBIAEoBEIMgrUYCFZpZGVvIElE",
            "Ej0KDWNsaWVudF9jZWxsaWQYAiABKA1CJoK1GCJDZWxsIElEIG9mIGNsaWVu",
            "dCwgemVybyBpZiB1bmtub3duInIKIUNWaWRlb19DbGllbnRHZXRWaWRlb1VS",
            "TF9SZXNwb25zZRIeCgh2aWRlb19pZBgBIAEoBEIMgrUYCFZpZGVvIElEEi0K",
            "CXZpZGVvX3VybBgCIAEoCUIagrUYFlVSTCBmb3IgdmlkZW8gbWFuaWZlc3Qi",
            "qgQKDVZpZGVvQm9va21hcmsSGgoGYXBwX2lkGAEgASgNQgqCtRgGQXBwIElE",
            "El0KHHBsYXliYWNrX3Bvc2l0aW9uX2luX3NlY29uZHMYAiABKA1CN4K1GDNI",
            "b3cgbWFueSBzZWNvbmRzIGludG8gdGhlIHZpZGVvIHRoZSBib29rbWFyayBp",
            "cyBmb3ISLwoOdmlkZW9fdHJhY2tfaWQYAyABKARCF4K1GBN2aWRlbyB0cmFj",
            "ayBjaG9pY2UuEi8KDmF1ZGlvX3RyYWNrX2lkGAQgASgEQheCtRgTYXVkaW8g",
            "dHJhY2sgY2hvaWNlLhJDChJ0aW1lZHRleHRfdHJhY2tfaWQYBSABKARCJ4K1",
            "GCN0aW1lZHRpbWVkIG9yIHN1YnRpdGxlIHRyYWNrIGNob2ljZRJPCg1sYXN0",
            "X21vZGlmaWVkGAYgASgNQjiCtRg0d2hlbiB3ZSByZWNvcmRlZCBpdCB3YXMg",
            "bGFzdCBtb2RpZmllZC4gTm90IHNldHRhYmxlLhJVChdoaWRlX2Zyb21fd2F0",
            "Y2hfaGlzdG9yeRgHIAEoCDoFZmFsc2VCLYK1GClXaGV0aGVyIEkgd2FudCB0",
            "byBzaG93IHRoaXMgaW4gbXkgaGlzdG9yeRJPChFoaWRlX2Zyb21fbGlicmFy",
            "eRgIIAEoCDoFZmFsc2VCLYK1GClXaGV0aGVyIEkgd2FudCB0byBzaG93IHRo",
            "aXMgaW4gbXkgbGlicmFyeSJyCiRDVmlkZW9fU2V0VmlkZW9Cb29rbWFya19O",
            "b3RpZmljYXRpb24SSgoJYm9va21hcmtzGAEgAygLMg4uVmlkZW9Cb29rbWFy",
            "a0IngrUYI2xpc3Qgb2YgYm9va21hcmtzIHdlIHdhbnQgdG8gc3RvcmUuIoEC",
            "CiBDVmlkZW9fR2V0VmlkZW9Cb29rbWFya3NfUmVxdWVzdBJfCgZhcHBpZHMY",
            "ASADKA1CT4K1GEtMaXN0IG9mIEFwcCBJRHMgdG8gZ3JhYiBib29rbWFya3Mg",
            "Zm9yLiBDYW4gYmUgZW1wdHkgaWYgdXNpbmcgdXBkYXRlZF9zaW5jZS4SfAoN",
            "dXBkYXRlZF9zaW5jZRgCIAEoDUJlgrUYYU9ubHkgcmV0dXJuIHJlc3VsdHMg",
            "YWZ0ZXIgdGltZS4gTWluIHZhbHVlIGlzIDEuIChzZWNvbmRzIHNpbmNlIGVw",
            "b2NoIEphbnVhcnkgMXN0LCAxOTcwIFVuaXggVGltZSkidQohQ1ZpZGVvX0dl",
            "dFZpZGVvQm9va21hcmtzX1Jlc3BvbnNlElAKCWJvb2ttYXJrcxgBIAMoCzIO",
            "LlZpZGVvQm9va21hcmtCLYK1GClMaXN0IG9mIGJvb2ttYXJrcyB3ZSBmb3Vu",
            "ZC4gQ2FuIGJlIGVtcHR5LiI6CiBDVmlkZW9fVW5sb2NrZWRIMjY0X05vdGlm",
            "aWNhdGlvbhIWCg5lbmNyeXB0aW9uX2tleRgBIAEoDCKFAQooQ0ZvdmFzVmlk",
            "ZW9fQ2xpZW50R2V0T1BGU2V0dGluZ3NfUmVxdWVzdBIaCgZhcHBfaWQYASAB",
            "KA1CCoK1GAZBcHAgSUQSPQoNY2xpZW50X2NlbGxpZBgCIAEoDUImgrUYIkNl",
            "bGwgSUQgb2YgY2xpZW50LCB6ZXJvIGlmIHVua25vd24ifAopQ0ZvdmFzVmlk",
            "ZW9fQ2xpZW50R2V0T1BGU2V0dGluZ3NfUmVzcG9uc2USGgoGYXBwX2lkGAEg",
            "ASgNQgqCtRgGQXBwIElEEjMKDG9wZl9zZXR0aW5ncxgCIAEoCUIdgrUYGUpT",
            "T04gYmxvYiBvZiBPUEYgU2V0dGluZ3MytQQKBVZpZGVvEo4BChFDbGllbnRH",
            "ZXRWaWRlb1VSTBIhLkNWaWRlb19DbGllbnRHZXRWaWRlb1VSTF9SZXF1ZXN0",
            "GiIuQ1ZpZGVvX0NsaWVudEdldFZpZGVvVVJMX1Jlc3BvbnNlIjKCtRguR2V0",
            "IHRoZSBpbml0aWFsIFVSTCB0byBiZWdpbiBzdHJlYW1pbmcgYSB2aWRlbxLB",
            "AQoQU2V0VmlkZW9Cb29rbWFyaxIlLkNWaWRlb19TZXRWaWRlb0Jvb2ttYXJr",
            "X05vdGlmaWNhdGlvbhoLLk5vUmVzcG9uc2UieYK1GHVCb29rbWFya3MgdGhl",
            "IGxvY2F0aW9ucyBpbiB0aGUgdmlkZW8gdGhlIHVzZXIgaGFzIHJlYWNoZWQu",
            "IEFzIGFzIHJlY29yZCBwbGF5YmFjayBzZXR0aW5ncyBwZXIgdmlkZW8uIEZp",
            "cmUgYW5kIGZvcmdldC4SwwEKEUdldFZpZGVvQm9va21hcmtzEiEuQ1ZpZGVv",
            "X0dldFZpZGVvQm9va21hcmtzX1JlcXVlc3QaIi5DVmlkZW9fR2V0VmlkZW9C",
            "b29rbWFya3NfUmVzcG9uc2UiZ4K1GGNSZXR1cm5zIHRoZSB2aWRlbyBib29r",
            "bWFya3MgbG9jYXRpb25zIGZvciB0aGUgc3BlY2lmaWMgdmlkZW9zLiBJbmNs",
            "dWRlcyBwbGF5YmFjayBzZXR0aW5ncyBwZXIgdmlkZW8aEYK1GA1WaWRlbyBt",
            "ZXRob2RzMp4BCgtWaWRlb0NsaWVudBKIAQoSTm90aWZ5VW5sb2NrZWRIMjY0",
            "EiEuQ1ZpZGVvX1VubG9ja2VkSDI2NF9Ob3RpZmljYXRpb24aCy5Ob1Jlc3Bv",
            "bnNlIkKCtRg+Tm90aWZpY2F0aW9uIGZyb20gc2VydmVyIHRvIGNsaWVudCB0",
            "aGF0IGgyNjQgaGFzIGJlZW4gdW5sb2NrZWQaBMC1GAIy8wEKCkZvdmFzVmlk",
            "ZW8SwwEKFENsaWVudEdldE9QRlNldHRpbmdzEikuQ0ZvdmFzVmlkZW9fQ2xp",
            "ZW50R2V0T1BGU2V0dGluZ3NfUmVxdWVzdBoqLkNGb3Zhc1ZpZGVvX0NsaWVu",
            "dEdldE9QRlNldHRpbmdzX1Jlc3BvbnNlIlSCtRhQUmV0cmlldmUgdGhlIE9Q",
            "RiBzZXR0aW5ncyBKU09OIGJsb2IuIEF2YWlsYWJsZSB2aWEgdGhlIENsaWVu",
            "dCBmb3IgMzYwIFBsYXllciBBcHAaH4K1GBtGb3ZhcyBWaWRlbyBTZXJ2aWNl",
            "IE1ldGhvZHNCGoABAaoCFFN0ZWFtLk1lc3NhZ2VzLlZpZGVv"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Steam.Messages.Base.SteammessagesBaseReflection.Descriptor, global::Steam.Messages.Unified.Base.SteammessagesUnifiedBaseSteamclientReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CVideo_ClientGetVideoURL_Request), global::Steam.Messages.Video.CVideo_ClientGetVideoURL_Request.Parser, new[]{ "VideoId", "ClientCellid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CVideo_ClientGetVideoURL_Response), global::Steam.Messages.Video.CVideo_ClientGetVideoURL_Response.Parser, new[]{ "VideoId", "VideoUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.VideoBookmark), global::Steam.Messages.Video.VideoBookmark.Parser, new[]{ "AppId", "PlaybackPositionInSeconds", "VideoTrackId", "AudioTrackId", "TimedtextTrackId", "LastModified", "HideFromWatchHistory", "HideFromLibrary" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CVideo_SetVideoBookmark_Notification), global::Steam.Messages.Video.CVideo_SetVideoBookmark_Notification.Parser, new[]{ "Bookmarks" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CVideo_GetVideoBookmarks_Request), global::Steam.Messages.Video.CVideo_GetVideoBookmarks_Request.Parser, new[]{ "Appids", "UpdatedSince" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CVideo_GetVideoBookmarks_Response), global::Steam.Messages.Video.CVideo_GetVideoBookmarks_Response.Parser, new[]{ "Bookmarks" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CVideo_UnlockedH264_Notification), global::Steam.Messages.Video.CVideo_UnlockedH264_Notification.Parser, new[]{ "EncryptionKey" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CFovasVideo_ClientGetOPFSettings_Request), global::Steam.Messages.Video.CFovasVideo_ClientGetOPFSettings_Request.Parser, new[]{ "AppId", "ClientCellid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Steam.Messages.Video.CFovasVideo_ClientGetOPFSettings_Response), global::Steam.Messages.Video.CFovasVideo_ClientGetOPFSettings_Response.Parser, new[]{ "AppId", "OpfSettings" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CVideo_ClientGetVideoURL_Request : pb::IMessage<CVideo_ClientGetVideoURL_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CVideo_ClientGetVideoURL_Request> _parser = new pb::MessageParser<CVideo_ClientGetVideoURL_Request>(() => new CVideo_ClientGetVideoURL_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CVideo_ClientGetVideoURL_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_ClientGetVideoURL_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_ClientGetVideoURL_Request(CVideo_ClientGetVideoURL_Request other) : this() {
      _hasBits0 = other._hasBits0;
      videoId_ = other.videoId_;
      clientCellid_ = other.clientCellid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_ClientGetVideoURL_Request Clone() {
      return new CVideo_ClientGetVideoURL_Request(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private readonly static ulong VideoIdDefaultValue = 0UL;

    private ulong videoId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong VideoId {
      get { if ((_hasBits0 & 1) != 0) { return videoId_; } else { return VideoIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        videoId_ = value;
      }
    }
    /// <summary>Gets whether the "video_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVideoId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "video_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVideoId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "client_cellid" field.</summary>
    public const int ClientCellidFieldNumber = 2;
    private readonly static uint ClientCellidDefaultValue = 0;

    private uint clientCellid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ClientCellid {
      get { if ((_hasBits0 & 2) != 0) { return clientCellid_; } else { return ClientCellidDefaultValue; } }
      set {
        _hasBits0 |= 2;
        clientCellid_ = value;
      }
    }
    /// <summary>Gets whether the "client_cellid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasClientCellid {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "client_cellid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearClientCellid() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CVideo_ClientGetVideoURL_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CVideo_ClientGetVideoURL_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VideoId != other.VideoId) return false;
      if (ClientCellid != other.ClientCellid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasVideoId) hash ^= VideoId.GetHashCode();
      if (HasClientCellid) hash ^= ClientCellid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasVideoId) {
        output.WriteRawTag(8);
        output.WriteUInt64(VideoId);
      }
      if (HasClientCellid) {
        output.WriteRawTag(16);
        output.WriteUInt32(ClientCellid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasVideoId) {
        output.WriteRawTag(8);
        output.WriteUInt64(VideoId);
      }
      if (HasClientCellid) {
        output.WriteRawTag(16);
        output.WriteUInt32(ClientCellid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasVideoId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(VideoId);
      }
      if (HasClientCellid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ClientCellid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CVideo_ClientGetVideoURL_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasVideoId) {
        VideoId = other.VideoId;
      }
      if (other.HasClientCellid) {
        ClientCellid = other.ClientCellid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            VideoId = input.ReadUInt64();
            break;
          }
          case 16: {
            ClientCellid = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            VideoId = input.ReadUInt64();
            break;
          }
          case 16: {
            ClientCellid = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CVideo_ClientGetVideoURL_Response : pb::IMessage<CVideo_ClientGetVideoURL_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CVideo_ClientGetVideoURL_Response> _parser = new pb::MessageParser<CVideo_ClientGetVideoURL_Response>(() => new CVideo_ClientGetVideoURL_Response());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CVideo_ClientGetVideoURL_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_ClientGetVideoURL_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_ClientGetVideoURL_Response(CVideo_ClientGetVideoURL_Response other) : this() {
      _hasBits0 = other._hasBits0;
      videoId_ = other.videoId_;
      videoUrl_ = other.videoUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_ClientGetVideoURL_Response Clone() {
      return new CVideo_ClientGetVideoURL_Response(this);
    }

    /// <summary>Field number for the "video_id" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private readonly static ulong VideoIdDefaultValue = 0UL;

    private ulong videoId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong VideoId {
      get { if ((_hasBits0 & 1) != 0) { return videoId_; } else { return VideoIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        videoId_ = value;
      }
    }
    /// <summary>Gets whether the "video_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVideoId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "video_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVideoId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "video_url" field.</summary>
    public const int VideoUrlFieldNumber = 2;
    private readonly static string VideoUrlDefaultValue = "";

    private string videoUrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VideoUrl {
      get { return videoUrl_ ?? VideoUrlDefaultValue; }
      set {
        videoUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "video_url" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVideoUrl {
      get { return videoUrl_ != null; }
    }
    /// <summary>Clears the value of the "video_url" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVideoUrl() {
      videoUrl_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CVideo_ClientGetVideoURL_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CVideo_ClientGetVideoURL_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VideoId != other.VideoId) return false;
      if (VideoUrl != other.VideoUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasVideoId) hash ^= VideoId.GetHashCode();
      if (HasVideoUrl) hash ^= VideoUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasVideoId) {
        output.WriteRawTag(8);
        output.WriteUInt64(VideoId);
      }
      if (HasVideoUrl) {
        output.WriteRawTag(18);
        output.WriteString(VideoUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasVideoId) {
        output.WriteRawTag(8);
        output.WriteUInt64(VideoId);
      }
      if (HasVideoUrl) {
        output.WriteRawTag(18);
        output.WriteString(VideoUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasVideoId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(VideoId);
      }
      if (HasVideoUrl) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VideoUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CVideo_ClientGetVideoURL_Response other) {
      if (other == null) {
        return;
      }
      if (other.HasVideoId) {
        VideoId = other.VideoId;
      }
      if (other.HasVideoUrl) {
        VideoUrl = other.VideoUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            VideoId = input.ReadUInt64();
            break;
          }
          case 18: {
            VideoUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            VideoId = input.ReadUInt64();
            break;
          }
          case 18: {
            VideoUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class VideoBookmark : pb::IMessage<VideoBookmark>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VideoBookmark> _parser = new pb::MessageParser<VideoBookmark>(() => new VideoBookmark());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VideoBookmark> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VideoBookmark() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VideoBookmark(VideoBookmark other) : this() {
      _hasBits0 = other._hasBits0;
      appId_ = other.appId_;
      playbackPositionInSeconds_ = other.playbackPositionInSeconds_;
      videoTrackId_ = other.videoTrackId_;
      audioTrackId_ = other.audioTrackId_;
      timedtextTrackId_ = other.timedtextTrackId_;
      lastModified_ = other.lastModified_;
      hideFromWatchHistory_ = other.hideFromWatchHistory_;
      hideFromLibrary_ = other.hideFromLibrary_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VideoBookmark Clone() {
      return new VideoBookmark(this);
    }

    /// <summary>Field number for the "app_id" field.</summary>
    public const int AppIdFieldNumber = 1;
    private readonly static uint AppIdDefaultValue = 0;

    private uint appId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AppId {
      get { if ((_hasBits0 & 1) != 0) { return appId_; } else { return AppIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        appId_ = value;
      }
    }
    /// <summary>Gets whether the "app_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "app_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "playback_position_in_seconds" field.</summary>
    public const int PlaybackPositionInSecondsFieldNumber = 2;
    private readonly static uint PlaybackPositionInSecondsDefaultValue = 0;

    private uint playbackPositionInSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PlaybackPositionInSeconds {
      get { if ((_hasBits0 & 2) != 0) { return playbackPositionInSeconds_; } else { return PlaybackPositionInSecondsDefaultValue; } }
      set {
        _hasBits0 |= 2;
        playbackPositionInSeconds_ = value;
      }
    }
    /// <summary>Gets whether the "playback_position_in_seconds" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlaybackPositionInSeconds {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "playback_position_in_seconds" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlaybackPositionInSeconds() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "video_track_id" field.</summary>
    public const int VideoTrackIdFieldNumber = 3;
    private readonly static ulong VideoTrackIdDefaultValue = 0UL;

    private ulong videoTrackId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong VideoTrackId {
      get { if ((_hasBits0 & 4) != 0) { return videoTrackId_; } else { return VideoTrackIdDefaultValue; } }
      set {
        _hasBits0 |= 4;
        videoTrackId_ = value;
      }
    }
    /// <summary>Gets whether the "video_track_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasVideoTrackId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "video_track_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearVideoTrackId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "audio_track_id" field.</summary>
    public const int AudioTrackIdFieldNumber = 4;
    private readonly static ulong AudioTrackIdDefaultValue = 0UL;

    private ulong audioTrackId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong AudioTrackId {
      get { if ((_hasBits0 & 8) != 0) { return audioTrackId_; } else { return AudioTrackIdDefaultValue; } }
      set {
        _hasBits0 |= 8;
        audioTrackId_ = value;
      }
    }
    /// <summary>Gets whether the "audio_track_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAudioTrackId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "audio_track_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAudioTrackId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "timedtext_track_id" field.</summary>
    public const int TimedtextTrackIdFieldNumber = 5;
    private readonly static ulong TimedtextTrackIdDefaultValue = 0UL;

    private ulong timedtextTrackId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TimedtextTrackId {
      get { if ((_hasBits0 & 16) != 0) { return timedtextTrackId_; } else { return TimedtextTrackIdDefaultValue; } }
      set {
        _hasBits0 |= 16;
        timedtextTrackId_ = value;
      }
    }
    /// <summary>Gets whether the "timedtext_track_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimedtextTrackId {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "timedtext_track_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimedtextTrackId() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "last_modified" field.</summary>
    public const int LastModifiedFieldNumber = 6;
    private readonly static uint LastModifiedDefaultValue = 0;

    private uint lastModified_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LastModified {
      get { if ((_hasBits0 & 32) != 0) { return lastModified_; } else { return LastModifiedDefaultValue; } }
      set {
        _hasBits0 |= 32;
        lastModified_ = value;
      }
    }
    /// <summary>Gets whether the "last_modified" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLastModified {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "last_modified" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLastModified() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "hide_from_watch_history" field.</summary>
    public const int HideFromWatchHistoryFieldNumber = 7;
    private readonly static bool HideFromWatchHistoryDefaultValue = false;

    private bool hideFromWatchHistory_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HideFromWatchHistory {
      get { if ((_hasBits0 & 64) != 0) { return hideFromWatchHistory_; } else { return HideFromWatchHistoryDefaultValue; } }
      set {
        _hasBits0 |= 64;
        hideFromWatchHistory_ = value;
      }
    }
    /// <summary>Gets whether the "hide_from_watch_history" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHideFromWatchHistory {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "hide_from_watch_history" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHideFromWatchHistory() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "hide_from_library" field.</summary>
    public const int HideFromLibraryFieldNumber = 8;
    private readonly static bool HideFromLibraryDefaultValue = false;

    private bool hideFromLibrary_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HideFromLibrary {
      get { if ((_hasBits0 & 128) != 0) { return hideFromLibrary_; } else { return HideFromLibraryDefaultValue; } }
      set {
        _hasBits0 |= 128;
        hideFromLibrary_ = value;
      }
    }
    /// <summary>Gets whether the "hide_from_library" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHideFromLibrary {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "hide_from_library" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHideFromLibrary() {
      _hasBits0 &= ~128;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VideoBookmark);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VideoBookmark other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppId != other.AppId) return false;
      if (PlaybackPositionInSeconds != other.PlaybackPositionInSeconds) return false;
      if (VideoTrackId != other.VideoTrackId) return false;
      if (AudioTrackId != other.AudioTrackId) return false;
      if (TimedtextTrackId != other.TimedtextTrackId) return false;
      if (LastModified != other.LastModified) return false;
      if (HideFromWatchHistory != other.HideFromWatchHistory) return false;
      if (HideFromLibrary != other.HideFromLibrary) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAppId) hash ^= AppId.GetHashCode();
      if (HasPlaybackPositionInSeconds) hash ^= PlaybackPositionInSeconds.GetHashCode();
      if (HasVideoTrackId) hash ^= VideoTrackId.GetHashCode();
      if (HasAudioTrackId) hash ^= AudioTrackId.GetHashCode();
      if (HasTimedtextTrackId) hash ^= TimedtextTrackId.GetHashCode();
      if (HasLastModified) hash ^= LastModified.GetHashCode();
      if (HasHideFromWatchHistory) hash ^= HideFromWatchHistory.GetHashCode();
      if (HasHideFromLibrary) hash ^= HideFromLibrary.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAppId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AppId);
      }
      if (HasPlaybackPositionInSeconds) {
        output.WriteRawTag(16);
        output.WriteUInt32(PlaybackPositionInSeconds);
      }
      if (HasVideoTrackId) {
        output.WriteRawTag(24);
        output.WriteUInt64(VideoTrackId);
      }
      if (HasAudioTrackId) {
        output.WriteRawTag(32);
        output.WriteUInt64(AudioTrackId);
      }
      if (HasTimedtextTrackId) {
        output.WriteRawTag(40);
        output.WriteUInt64(TimedtextTrackId);
      }
      if (HasLastModified) {
        output.WriteRawTag(48);
        output.WriteUInt32(LastModified);
      }
      if (HasHideFromWatchHistory) {
        output.WriteRawTag(56);
        output.WriteBool(HideFromWatchHistory);
      }
      if (HasHideFromLibrary) {
        output.WriteRawTag(64);
        output.WriteBool(HideFromLibrary);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAppId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AppId);
      }
      if (HasPlaybackPositionInSeconds) {
        output.WriteRawTag(16);
        output.WriteUInt32(PlaybackPositionInSeconds);
      }
      if (HasVideoTrackId) {
        output.WriteRawTag(24);
        output.WriteUInt64(VideoTrackId);
      }
      if (HasAudioTrackId) {
        output.WriteRawTag(32);
        output.WriteUInt64(AudioTrackId);
      }
      if (HasTimedtextTrackId) {
        output.WriteRawTag(40);
        output.WriteUInt64(TimedtextTrackId);
      }
      if (HasLastModified) {
        output.WriteRawTag(48);
        output.WriteUInt32(LastModified);
      }
      if (HasHideFromWatchHistory) {
        output.WriteRawTag(56);
        output.WriteBool(HideFromWatchHistory);
      }
      if (HasHideFromLibrary) {
        output.WriteRawTag(64);
        output.WriteBool(HideFromLibrary);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAppId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AppId);
      }
      if (HasPlaybackPositionInSeconds) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlaybackPositionInSeconds);
      }
      if (HasVideoTrackId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(VideoTrackId);
      }
      if (HasAudioTrackId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AudioTrackId);
      }
      if (HasTimedtextTrackId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimedtextTrackId);
      }
      if (HasLastModified) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LastModified);
      }
      if (HasHideFromWatchHistory) {
        size += 1 + 1;
      }
      if (HasHideFromLibrary) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VideoBookmark other) {
      if (other == null) {
        return;
      }
      if (other.HasAppId) {
        AppId = other.AppId;
      }
      if (other.HasPlaybackPositionInSeconds) {
        PlaybackPositionInSeconds = other.PlaybackPositionInSeconds;
      }
      if (other.HasVideoTrackId) {
        VideoTrackId = other.VideoTrackId;
      }
      if (other.HasAudioTrackId) {
        AudioTrackId = other.AudioTrackId;
      }
      if (other.HasTimedtextTrackId) {
        TimedtextTrackId = other.TimedtextTrackId;
      }
      if (other.HasLastModified) {
        LastModified = other.LastModified;
      }
      if (other.HasHideFromWatchHistory) {
        HideFromWatchHistory = other.HideFromWatchHistory;
      }
      if (other.HasHideFromLibrary) {
        HideFromLibrary = other.HideFromLibrary;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AppId = input.ReadUInt32();
            break;
          }
          case 16: {
            PlaybackPositionInSeconds = input.ReadUInt32();
            break;
          }
          case 24: {
            VideoTrackId = input.ReadUInt64();
            break;
          }
          case 32: {
            AudioTrackId = input.ReadUInt64();
            break;
          }
          case 40: {
            TimedtextTrackId = input.ReadUInt64();
            break;
          }
          case 48: {
            LastModified = input.ReadUInt32();
            break;
          }
          case 56: {
            HideFromWatchHistory = input.ReadBool();
            break;
          }
          case 64: {
            HideFromLibrary = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AppId = input.ReadUInt32();
            break;
          }
          case 16: {
            PlaybackPositionInSeconds = input.ReadUInt32();
            break;
          }
          case 24: {
            VideoTrackId = input.ReadUInt64();
            break;
          }
          case 32: {
            AudioTrackId = input.ReadUInt64();
            break;
          }
          case 40: {
            TimedtextTrackId = input.ReadUInt64();
            break;
          }
          case 48: {
            LastModified = input.ReadUInt32();
            break;
          }
          case 56: {
            HideFromWatchHistory = input.ReadBool();
            break;
          }
          case 64: {
            HideFromLibrary = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CVideo_SetVideoBookmark_Notification : pb::IMessage<CVideo_SetVideoBookmark_Notification>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CVideo_SetVideoBookmark_Notification> _parser = new pb::MessageParser<CVideo_SetVideoBookmark_Notification>(() => new CVideo_SetVideoBookmark_Notification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CVideo_SetVideoBookmark_Notification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_SetVideoBookmark_Notification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_SetVideoBookmark_Notification(CVideo_SetVideoBookmark_Notification other) : this() {
      bookmarks_ = other.bookmarks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_SetVideoBookmark_Notification Clone() {
      return new CVideo_SetVideoBookmark_Notification(this);
    }

    /// <summary>Field number for the "bookmarks" field.</summary>
    public const int BookmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Steam.Messages.Video.VideoBookmark> _repeated_bookmarks_codec
        = pb::FieldCodec.ForMessage(10, global::Steam.Messages.Video.VideoBookmark.Parser);
    private readonly pbc::RepeatedField<global::Steam.Messages.Video.VideoBookmark> bookmarks_ = new pbc::RepeatedField<global::Steam.Messages.Video.VideoBookmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Steam.Messages.Video.VideoBookmark> Bookmarks {
      get { return bookmarks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CVideo_SetVideoBookmark_Notification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CVideo_SetVideoBookmark_Notification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!bookmarks_.Equals(other.bookmarks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= bookmarks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      bookmarks_.WriteTo(output, _repeated_bookmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      bookmarks_.WriteTo(ref output, _repeated_bookmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += bookmarks_.CalculateSize(_repeated_bookmarks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CVideo_SetVideoBookmark_Notification other) {
      if (other == null) {
        return;
      }
      bookmarks_.Add(other.bookmarks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            bookmarks_.AddEntriesFrom(input, _repeated_bookmarks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            bookmarks_.AddEntriesFrom(ref input, _repeated_bookmarks_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CVideo_GetVideoBookmarks_Request : pb::IMessage<CVideo_GetVideoBookmarks_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CVideo_GetVideoBookmarks_Request> _parser = new pb::MessageParser<CVideo_GetVideoBookmarks_Request>(() => new CVideo_GetVideoBookmarks_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CVideo_GetVideoBookmarks_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_GetVideoBookmarks_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_GetVideoBookmarks_Request(CVideo_GetVideoBookmarks_Request other) : this() {
      _hasBits0 = other._hasBits0;
      appids_ = other.appids_.Clone();
      updatedSince_ = other.updatedSince_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_GetVideoBookmarks_Request Clone() {
      return new CVideo_GetVideoBookmarks_Request(this);
    }

    /// <summary>Field number for the "appids" field.</summary>
    public const int AppidsFieldNumber = 1;
    private static readonly pb::FieldCodec<uint> _repeated_appids_codec
        = pb::FieldCodec.ForUInt32(8);
    private readonly pbc::RepeatedField<uint> appids_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Appids {
      get { return appids_; }
    }

    /// <summary>Field number for the "updated_since" field.</summary>
    public const int UpdatedSinceFieldNumber = 2;
    private readonly static uint UpdatedSinceDefaultValue = 0;

    private uint updatedSince_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UpdatedSince {
      get { if ((_hasBits0 & 1) != 0) { return updatedSince_; } else { return UpdatedSinceDefaultValue; } }
      set {
        _hasBits0 |= 1;
        updatedSince_ = value;
      }
    }
    /// <summary>Gets whether the "updated_since" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUpdatedSince {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "updated_since" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUpdatedSince() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CVideo_GetVideoBookmarks_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CVideo_GetVideoBookmarks_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!appids_.Equals(other.appids_)) return false;
      if (UpdatedSince != other.UpdatedSince) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= appids_.GetHashCode();
      if (HasUpdatedSince) hash ^= UpdatedSince.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      appids_.WriteTo(output, _repeated_appids_codec);
      if (HasUpdatedSince) {
        output.WriteRawTag(16);
        output.WriteUInt32(UpdatedSince);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      appids_.WriteTo(ref output, _repeated_appids_codec);
      if (HasUpdatedSince) {
        output.WriteRawTag(16);
        output.WriteUInt32(UpdatedSince);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += appids_.CalculateSize(_repeated_appids_codec);
      if (HasUpdatedSince) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UpdatedSince);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CVideo_GetVideoBookmarks_Request other) {
      if (other == null) {
        return;
      }
      appids_.Add(other.appids_);
      if (other.HasUpdatedSince) {
        UpdatedSince = other.UpdatedSince;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            appids_.AddEntriesFrom(input, _repeated_appids_codec);
            break;
          }
          case 16: {
            UpdatedSince = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            appids_.AddEntriesFrom(ref input, _repeated_appids_codec);
            break;
          }
          case 16: {
            UpdatedSince = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CVideo_GetVideoBookmarks_Response : pb::IMessage<CVideo_GetVideoBookmarks_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CVideo_GetVideoBookmarks_Response> _parser = new pb::MessageParser<CVideo_GetVideoBookmarks_Response>(() => new CVideo_GetVideoBookmarks_Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CVideo_GetVideoBookmarks_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_GetVideoBookmarks_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_GetVideoBookmarks_Response(CVideo_GetVideoBookmarks_Response other) : this() {
      bookmarks_ = other.bookmarks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_GetVideoBookmarks_Response Clone() {
      return new CVideo_GetVideoBookmarks_Response(this);
    }

    /// <summary>Field number for the "bookmarks" field.</summary>
    public const int BookmarksFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Steam.Messages.Video.VideoBookmark> _repeated_bookmarks_codec
        = pb::FieldCodec.ForMessage(10, global::Steam.Messages.Video.VideoBookmark.Parser);
    private readonly pbc::RepeatedField<global::Steam.Messages.Video.VideoBookmark> bookmarks_ = new pbc::RepeatedField<global::Steam.Messages.Video.VideoBookmark>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Steam.Messages.Video.VideoBookmark> Bookmarks {
      get { return bookmarks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CVideo_GetVideoBookmarks_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CVideo_GetVideoBookmarks_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!bookmarks_.Equals(other.bookmarks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= bookmarks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      bookmarks_.WriteTo(output, _repeated_bookmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      bookmarks_.WriteTo(ref output, _repeated_bookmarks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += bookmarks_.CalculateSize(_repeated_bookmarks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CVideo_GetVideoBookmarks_Response other) {
      if (other == null) {
        return;
      }
      bookmarks_.Add(other.bookmarks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            bookmarks_.AddEntriesFrom(input, _repeated_bookmarks_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            bookmarks_.AddEntriesFrom(ref input, _repeated_bookmarks_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CVideo_UnlockedH264_Notification : pb::IMessage<CVideo_UnlockedH264_Notification>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CVideo_UnlockedH264_Notification> _parser = new pb::MessageParser<CVideo_UnlockedH264_Notification>(() => new CVideo_UnlockedH264_Notification());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CVideo_UnlockedH264_Notification> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_UnlockedH264_Notification() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_UnlockedH264_Notification(CVideo_UnlockedH264_Notification other) : this() {
      encryptionKey_ = other.encryptionKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CVideo_UnlockedH264_Notification Clone() {
      return new CVideo_UnlockedH264_Notification(this);
    }

    /// <summary>Field number for the "encryption_key" field.</summary>
    public const int EncryptionKeyFieldNumber = 1;
    private readonly static pb::ByteString EncryptionKeyDefaultValue = pb::ByteString.Empty;

    private pb::ByteString encryptionKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString EncryptionKey {
      get { return encryptionKey_ ?? EncryptionKeyDefaultValue; }
      set {
        encryptionKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "encryption_key" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEncryptionKey {
      get { return encryptionKey_ != null; }
    }
    /// <summary>Clears the value of the "encryption_key" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEncryptionKey() {
      encryptionKey_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CVideo_UnlockedH264_Notification);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CVideo_UnlockedH264_Notification other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EncryptionKey != other.EncryptionKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEncryptionKey) hash ^= EncryptionKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEncryptionKey) {
        output.WriteRawTag(10);
        output.WriteBytes(EncryptionKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEncryptionKey) {
        output.WriteRawTag(10);
        output.WriteBytes(EncryptionKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEncryptionKey) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EncryptionKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CVideo_UnlockedH264_Notification other) {
      if (other == null) {
        return;
      }
      if (other.HasEncryptionKey) {
        EncryptionKey = other.EncryptionKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EncryptionKey = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EncryptionKey = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CFovasVideo_ClientGetOPFSettings_Request : pb::IMessage<CFovasVideo_ClientGetOPFSettings_Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CFovasVideo_ClientGetOPFSettings_Request> _parser = new pb::MessageParser<CFovasVideo_ClientGetOPFSettings_Request>(() => new CFovasVideo_ClientGetOPFSettings_Request());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CFovasVideo_ClientGetOPFSettings_Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CFovasVideo_ClientGetOPFSettings_Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CFovasVideo_ClientGetOPFSettings_Request(CFovasVideo_ClientGetOPFSettings_Request other) : this() {
      _hasBits0 = other._hasBits0;
      appId_ = other.appId_;
      clientCellid_ = other.clientCellid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CFovasVideo_ClientGetOPFSettings_Request Clone() {
      return new CFovasVideo_ClientGetOPFSettings_Request(this);
    }

    /// <summary>Field number for the "app_id" field.</summary>
    public const int AppIdFieldNumber = 1;
    private readonly static uint AppIdDefaultValue = 0;

    private uint appId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AppId {
      get { if ((_hasBits0 & 1) != 0) { return appId_; } else { return AppIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        appId_ = value;
      }
    }
    /// <summary>Gets whether the "app_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "app_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "client_cellid" field.</summary>
    public const int ClientCellidFieldNumber = 2;
    private readonly static uint ClientCellidDefaultValue = 0;

    private uint clientCellid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ClientCellid {
      get { if ((_hasBits0 & 2) != 0) { return clientCellid_; } else { return ClientCellidDefaultValue; } }
      set {
        _hasBits0 |= 2;
        clientCellid_ = value;
      }
    }
    /// <summary>Gets whether the "client_cellid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasClientCellid {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "client_cellid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearClientCellid() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CFovasVideo_ClientGetOPFSettings_Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CFovasVideo_ClientGetOPFSettings_Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppId != other.AppId) return false;
      if (ClientCellid != other.ClientCellid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAppId) hash ^= AppId.GetHashCode();
      if (HasClientCellid) hash ^= ClientCellid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAppId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AppId);
      }
      if (HasClientCellid) {
        output.WriteRawTag(16);
        output.WriteUInt32(ClientCellid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAppId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AppId);
      }
      if (HasClientCellid) {
        output.WriteRawTag(16);
        output.WriteUInt32(ClientCellid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAppId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AppId);
      }
      if (HasClientCellid) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ClientCellid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CFovasVideo_ClientGetOPFSettings_Request other) {
      if (other == null) {
        return;
      }
      if (other.HasAppId) {
        AppId = other.AppId;
      }
      if (other.HasClientCellid) {
        ClientCellid = other.ClientCellid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AppId = input.ReadUInt32();
            break;
          }
          case 16: {
            ClientCellid = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AppId = input.ReadUInt32();
            break;
          }
          case 16: {
            ClientCellid = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CFovasVideo_ClientGetOPFSettings_Response : pb::IMessage<CFovasVideo_ClientGetOPFSettings_Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CFovasVideo_ClientGetOPFSettings_Response> _parser = new pb::MessageParser<CFovasVideo_ClientGetOPFSettings_Response>(() => new CFovasVideo_ClientGetOPFSettings_Response());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CFovasVideo_ClientGetOPFSettings_Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Steam.Messages.Video.SteammessagesVideoSteamclientReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CFovasVideo_ClientGetOPFSettings_Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CFovasVideo_ClientGetOPFSettings_Response(CFovasVideo_ClientGetOPFSettings_Response other) : this() {
      _hasBits0 = other._hasBits0;
      appId_ = other.appId_;
      opfSettings_ = other.opfSettings_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CFovasVideo_ClientGetOPFSettings_Response Clone() {
      return new CFovasVideo_ClientGetOPFSettings_Response(this);
    }

    /// <summary>Field number for the "app_id" field.</summary>
    public const int AppIdFieldNumber = 1;
    private readonly static uint AppIdDefaultValue = 0;

    private uint appId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AppId {
      get { if ((_hasBits0 & 1) != 0) { return appId_; } else { return AppIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        appId_ = value;
      }
    }
    /// <summary>Gets whether the "app_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "app_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "opf_settings" field.</summary>
    public const int OpfSettingsFieldNumber = 2;
    private readonly static string OpfSettingsDefaultValue = "";

    private string opfSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OpfSettings {
      get { return opfSettings_ ?? OpfSettingsDefaultValue; }
      set {
        opfSettings_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "opf_settings" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOpfSettings {
      get { return opfSettings_ != null; }
    }
    /// <summary>Clears the value of the "opf_settings" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOpfSettings() {
      opfSettings_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CFovasVideo_ClientGetOPFSettings_Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CFovasVideo_ClientGetOPFSettings_Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppId != other.AppId) return false;
      if (OpfSettings != other.OpfSettings) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAppId) hash ^= AppId.GetHashCode();
      if (HasOpfSettings) hash ^= OpfSettings.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAppId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AppId);
      }
      if (HasOpfSettings) {
        output.WriteRawTag(18);
        output.WriteString(OpfSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAppId) {
        output.WriteRawTag(8);
        output.WriteUInt32(AppId);
      }
      if (HasOpfSettings) {
        output.WriteRawTag(18);
        output.WriteString(OpfSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAppId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AppId);
      }
      if (HasOpfSettings) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpfSettings);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CFovasVideo_ClientGetOPFSettings_Response other) {
      if (other == null) {
        return;
      }
      if (other.HasAppId) {
        AppId = other.AppId;
      }
      if (other.HasOpfSettings) {
        OpfSettings = other.OpfSettings;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AppId = input.ReadUInt32();
            break;
          }
          case 18: {
            OpfSettings = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AppId = input.ReadUInt32();
            break;
          }
          case 18: {
            OpfSettings = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
